ptkokushi/urls.py
from . import views
from django.urls import path

app_name = 'ptkokushi'

urlpatterns = [
    path('signup/', views.signup_view, name='signup'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('user/', views.user_view, name='user'),
    path('other/', views.other_view, name='other'),
]

ptproject/urls.py
from django.contrib import admin
from django.urls import path
from ptkokushi import views
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.TopView.as_view(), name="top"),
    path('login_app/', include('ptkokushi.urls')),
]

ptkokushi/models.py
from django.contrib import admin
from django.db import models


class birthday(models.Model):
    birthday = models.DateField()

    def __int__(self):
        return self.birthday

ptkokushi/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.admin.widgets import AdminDateWidget
from django.db import models


class SignupForm(UserCreationForm):
    birth_date = forms.DateField(
        help_text='必須: YYYY-MM-DD 形式で入力して下さい。',
        label='誕生日',
    )

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']

class LoginForm(AuthenticationForm):
    pass

ptkokushi/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.views.generic import TemplateView
from .forms import SignupForm, LoginForm
from django.contrib.auth import login, logout
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required

# Create your views here.
class TopView(TemplateView):
    template_name = "top.html"

#ユーザーアカウントの登録
def signup_view(request):
    if request.method == 'POST':

        form = SignupForm(request.POST)
        if form.is_valid():
            form.save()

    else:
        form = SignupForm()
    
    param = {
        'form': form
    }

    return render(request, 'login_app/signup.html', param)

#ユーザーのログイン
def login_view(request):
    if request.method == 'POST':
        next = request.POST.get('next')
        form = LoginForm(request, data=request.POST)

        if form.is_valid():
            user = form.get_user()

            if user:
                login(request, user)
                if next == 'None':
                    return redirect(to='top')
                else:
                    return redirect(to=next)
    else:
        form = LoginForm()
        next = request.GET.get('next')

    param = {
        'form': form,
        'next': next
    }

    return render(request, 'login_app/login.html', param)

#ユーザーのログアウト
def logout_view(request):
    logout(request)

    return render(request, 'login_app/logout.html')

#ログインユーザーの情報の表示
@login_required #未ログインユーザーからのアクセス禁止用の View の設定
def user_view(request):
    user = request.user

    params = {
        'user': user
    }

    return render(request, 'login_app/user.html', params)


#他のユーザーの情報の表示
@login_required #未ログインユーザーからのアクセス禁止用の View の設定
def other_view(request):
    users = User.objects.exclude(username=request.user.username)

    params = {
        'users': users
    }

    return render(request, 'login_app/other.html', params)


 

ptkokushi/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock %}</title>
    <!--boostrapの読み込み-->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
    <!--CSSの読み込み-->
    <link href="{% static 'css/style.css' %}" rel="stylesheet">
</head>
    
    <body>
        <!--コンテンツは以下に記述する-->
        <div class = "container">
            {% block content %}{% endblock %}
        </div>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe" crossorigin="anonymous"></script>
        <script src="static/javascript/kokushi.js"></script>
        <script src="static/javascript/timer.js"></script>
    </body>
    </html>        

ptkokushi/templates/login_app/login.html
{% load static %}
<!doctype html>
<html lang="ja">
<head>
    <meta charset="utf-8">
    <title>ログイン</title>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
<body>
    <body>
        <div class="login">
          <div class="login-screen">
            <div class="app-title">
              <h1 class = "app-title2">理学療法士<br>国試対策アプリ<br>ログイン画面</h1>
            </div>
            <form action="{% url 'ptkokushi:login' %}" method="post">
                {% csrf_token %}
                    {{ form.as_p }}
                    <p><input type="hidden" name="next" value="{{next}}"></p>
                    <p><input type="submit" value="ログイン"></p>
            </form>
            <form action = "{% url 'ptkokushi:signup' %}">
              <button id = "signup_form">アカウント新規作成</button>
            </form>  
          </div>
        </div>
      </body>
    </div>
</body>
</html>

ptkokushi/templates/login_app/logout.html
{% load static %}
<!doctype html>
<html lang="ja">
<head>
    <meta charset="utf-8">
    <title>ログアウト</title>
</head>
<body>
    <p>ログアウトしました...</p>
</body>

</html>

ptkokushi/templates/login_app/other.html
{% load static %}
<!doctype html>
<html lang="ja">
<head>
    <meta charset="utf-8">
    <title>他のユーザーの情報</title>
</head>
<body>
    <h1>他のユーザーの情報</h1>
    {% for user in users %}
    <h2>{{user.username}}</h2>
    <p>連絡先：{{user.email}}</p>
    {% endfor %}
</body>

</html>

ptkokushi/templates/login_app/signup.html
{% load static %}
<!doctype html>
<html lang="ja">
<head>
    <meta charset="utf-8">
    <title>ユーザー登録</title>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>
<body>
    <div id="container">
        <div class="signup-screen">
            <div class="space-bot text-center">
                <h1 id = "user_signup">ユーザー登録</h1>
                <form action="{% url 'ptkokushi:signup' %}" method="post">
                {% csrf_token %}
                {{ form.as_p }}
                <p><input class = "button-two" type="submit" value="登録"></p>
                </form>
            </div>
        </div>            
    <div>
</body>
</html>

ptkokushi/templates/login_app/user.html
{% load static %}
<!doctype html>
<html lang="ja">
<head>
    <meta charset="utf-8">
    <title>あなたの情報</title>
</head>
<body>
    <h1>{{user.username}}</h1>
    <p>連絡先：{{user.email}}</p>
    <p>アカウント作成日：{{user.date_joined}}</p>
</body>

</html>

ptkokushi/templates/question.html/58question.html
{% extends "base.html" %}
{% block title %}第58回 理学療法国家試験{% endblock%}
{% block content %}


{% endblock %}

ptkokushi/templates/top.html
{% extends "base.html" %}
{% block title %}理学療法国試対策{% endblock%}
{% block content %}
<div id = "all-display">
<div id = "top-nav">
    <div class = "title" backgroud = "img/reha.top.jpg">
        <h1 id = "title_top">理学療法国試対策アプリ</h1>
    </div>
    <div id = "timelimit" name = "year_number">
        <select id = "select_year">
            <option value = "59_year">第59回</option>
            <option value = "60_year">第60回</option>
            <option value = "61_year">第61回</option>
            <option value = "62_year">第62回</option>
        </select>            
    <p class = "atdays">
       国試まであと</p>
    <p id = "countTimer"></p>   
    </div> 
</div>

<div id="countdown">
</div>

<div = id = "side-quest">
    <div id = "side-bar">
        <p class = "button-001" id = "grade">成績</p>
        <p class = "button-001" id = "category">分野ごと</p>
        <p class = "button-001" id = "year">年度ごと</p>
        <p class = "button-001" id = "bookmark">ブックマーク問題</p>
        <p class = "button-001" id = "random">ランダム問題</p>
        <p class = "button-001" iD = "three-q">3点問題のみ</p>
        <p class = "button-001" is = "study-mode">学習モード</p>
        <p class = "button-001" id = "goal">目標設定</p>
    </div>
    <div id = "national-examination">
        <div class = "button national-year even" id = "58-year">第58回</div>
        <p class = "button national-year odd" id = "57-year">第57回</p>
        <p class = "button national-year even" id = "56-year">第56回</p>
        <p class = "button national-year odd" id = "55-year">第55回</p>
        <p class = "button national-year even" id = "54-year">第54回</p>
        <p class = "button national-year odd" id = "53-year">第53回</p>
        <p class = "button national-year even" id = "52-year">第52回</p>
        <p class = "button national-year odd" id = "51-year">第51回</p>
        <p class = "button national-year even" id = "50-year">第50回</p>
        <p class = "button national-year odd" id = "49-year">第49回</p>
    </div>    
</div>
</div>
{% endblock %}